// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Ikigai Garden",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Ikigai Garden",
            targets: ["App"],
            bundleIdentifier: "com.mikhail.boriosv.Ikigai-Garden",
            teamIdentifier: "38BRD9SJV7",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .healthcareFitness,
            additionalInfoPlistContentFilePath: "App/Info.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "App",
            path: "App",
            exclude: ["./Info.plist"],
            resources: [
                .process("Resources")
            ]
        )
    ]
)
